// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzbrQliYA4jB4yu01iinZ3fr5FZG987uI',
    appId: '1:648180542221:web:5e840503579837684f5e44',
    messagingSenderId: '648180542221',
    projectId: 'isave-f59e7',
    authDomain: 'isave-f59e7.firebaseapp.com',
    storageBucket: 'isave-f59e7.firebasestorage.app',
    measurementId: 'G-EFR901LJSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCldjK19LV3DRBRJIcs5H9XuCxmPvwcwIQ',
    appId: '1:648180542221:android:1bca123464e6eece4f5e44',
    messagingSenderId: '648180542221',
    projectId: 'isave-f59e7',
    storageBucket: 'isave-f59e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtowdQ-6cfKYIhQbklK5GRAPlc9bg108Q',
    appId: '1:648180542221:ios:427da3fe1c2e76864f5e44',
    messagingSenderId: '648180542221',
    projectId: 'isave-f59e7',
    storageBucket: 'isave-f59e7.firebasestorage.app',
    iosBundleId: 'com.example.isave',
  );
}
